apiVersion: v1
kind: Service
metadata:
  name: {{ include "hytale-server.name" . }}
  namespace: {{ include "hytale-server.namespace" . }}
  labels: {{- include "hytale-server.labels" . | nindent 4 }}
spec:
  selector: {{- include "hytale-server.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
